FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["razor1.csproj", "./"]
RUN dotnet restore "./razor1.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "razor1.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "razor1.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "razor1.dll"]
