FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["01-container.csproj", "./"]
RUN dotnet restore "01-container.csproj"
COPY . ./
RUN dotnet build "01-container.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "01-container.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "01-container.dll"]
